'use client'
import { useSession } from 'next-auth/react'
// import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { useEffect, useState } from 'react'
import { usePathname } from 'next/navigation'
import { Toast } from '@/components/ui/toast'
import { ToastProvider } from '@/components/ui/toast'
// import Navbar from '@/components/Navbar'
// import Providers from '@/components/Providers'
// import { Context } from '@/lib/context'
// import { useSession } from 'next-auth/react'
// import Navigation from './components/Navigation'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Course',
    description: 'Generated by create next app',
}

export default function CourseLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const searchParams = useSearchParams();
    const pathName = usePathname();
    const { data: session, status } = useSession();
    // const [currentPath,setCurrentPath] = useState();
    const { course_id, teacher_id, student_id } = { course_id: searchParams.get('course_id'), teacher_id: searchParams.get('teacher_id'), student_id: searchParams.get('student_id') };
    // const course_name = "Course";
    // console.log(course_id,teacher_id,student_id);
    console.log(status)
    const [activeButton, setActiveButton] = useState<string>();
    const [ourData, setOurData] = useState();
    const [at, setAt] = useState(false);
    const handleButtonClick = (buttonName: string) => {
        setActiveButton(buttonName);
    };

    useEffect(() => {
        const  pa = pathName.split(/[/]/);
        // console.log('path name: ', pa[3])
        setActiveButton(prev => pa[3])
    },[pathName])

    useEffect(() => {
        // console.log('saad: ', status);
        if (status === 'authenticated') {
            console.log('saad: ', status);
            fetch(`http://localhost:3000/api/assignment?course_id=${course_id}&teacher_id=${teacher_id}&student_id=${student_id}`, {
                method: 'GET',
                headers: {
                    authorization: `Bearer ${session.user.accessToken}`
                }
            }).then(res => res.json()).then(data => { setOurData(prev => data); console.log(data) })
        }
    }, [status])


    // const {data:session} = useSession();

    if (status === 'authenticated' && ourData) {
        // console.log(ourData)
        return (
            <ToastProvider>
            <section>
                <div className="md:ml-[90px] mx-6 mb-4">
                    <div className="my-4 px-2 pt-2 pb-8 bg-white border-2 shadow-md h-auto flex flex-col items-start">
                        <p className="text-3xl sm:text-4xl ml-4 font-medium tracking-normal leading-relaxed">
                            {/* {ourData[0].course_name} */}
                        </p>
                        <div className="mt-4 ml-4 flex flex-wrap">
                            <div className="p-2 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-sm">
                                <Link href={"/"} className="hover:underline">
                                    Dashboard
                                </Link>
                            </div>
                            <div className="p-2 bg-slate-100 mr-2 mb-2 lg:mb-0  rounded-sm">
                                <Link href={"/"} className="hover:underline">
                                    My Courses
                                </Link>
                            </div>
                            <div className="p-2 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-sm">
                                <Link href={"/"} className="hover:underline">
                                    Spring 2023
                                </Link>
                            </div>
                            <div className="p-2 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-sm">
                                <Link href={"/"} className="hover:underline">
                                    Computer Science
                                </Link>
                            </div>
                            <div className="p-2 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-sm">
                                <Link href={"/"} className="hover:underline">
                                    CS-2103-CS-222-BS-CS-4C
                                </Link>
                            </div>
                        </div>
                    </div>
                    <div className="border-2 border-t-2 border-t-black p-2 flex flex-wrap">
                        <button
                            className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "material"
                                ? "bg-black text-white"
                                : "bg-slate-200"
                                }`}
                            onClick={() => handleButtonClick("button1")}
                        >
                            <Link href={{ pathname: "/my/course/material", query: { course_id, teacher_id, student_id } }}>Lecture Slides</Link>
                        </button>
                        <button
                            className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "attendance"
                                ? "bg-black text-white"
                                : "bg-slate-200"
                                }`}
                            onClick={() => handleButtonClick("button2")}
                        >
                            <Link href={{ pathname: "/my/course/attendance", query: { course_id, teacher_id, student_id } }} onClick={() => setAt(!at)}>
                                Attendance
                            </Link>
                        </button>
                        <button
                            className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "announcement"
                                ? "bg-black text-white"
                                : "bg-slate-200"
                                }`}
                            onClick={() => handleButtonClick("button3")}
                        >
                            <Link href={{ pathname: "/my/course/announcement", query: { course_id, teacher_id, student_id } }}>Announcement</Link>
                        </button>
                        <button
                            className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "assignment"
                                ? "bg-black text-white"
                                : "bg-slate-200"
                                }`}
                            onClick={() => handleButtonClick("button4")}
                        >
                            <Link href={{ pathname: "/my/course/assignment", query: { course_id, teacher_id, student_id } }}>Assignment</Link>
                        </button>
                        <button
                            className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "quiz"
                                ? "bg-black text-white"
                                : "bg-slate-200"
                                }`}
                            onClick={() => handleButtonClick("button5")}
                        >
                            <Link href={{ pathname: "/my/course/quiz", query: { course_id, teacher_id, student_id } }}>Quiz</Link>
                        </button>
                    </div>
                    <div className="border-2 h-full mt-4 duration-500 p-4">
                        {children}
                    </div>
                    {/* {activeButton === "button1" ? (
          <LectureSlide />
      ) : activeButton === "button2" ? (
          <Attendance />
      ) : activeButton === "button3" ? (
        <Announcement />
        ) : activeButton === "button4" ? (
            <Assignment />
            ) : activeButton === "button5" ? (
                <Quiz />
                ) : (
                    <LectureSlide />
                    )} */}
                    {/* </div>  */}
                </div>
                <Toast/>
            </section>
            </ToastProvider>
        );
    }

    // return (
    //     <html lang="en">
    //         <body className={inter.className}>
    //             <p>LOADING...</p>
    //             {children}
    //         </body>
    //     </html>
    // )
}
