'use client'
import { useSession } from 'next-auth/react'
// import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { useEffect, useState } from 'react'
import { usePathname } from 'next/navigation'
// import Navbar from '@/components/Navbar'
// import Providers from '@/components/Providers'
// import { Context } from '@/lib/context'
// import { useSession } from 'next-auth/react'
// import Navigation from './components/Navigation'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Course',
    description: 'Generated by create next app',
}

export default function CourseLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const searchParams = useSearchParams();
    const pathName = usePathname();
    const { data: session, status } = useSession();
    // const [currentPath,setCurrentPath] = useState();
    const { course_id, teacher_id, student_id } = { course_id: searchParams.get('course_id'), teacher_id: searchParams.get('teacher_id'), student_id: searchParams.get('student_id') };
    // const course_name = "Course";
    // console.log(course_id,teacher_id,student_id);
    console.log(status)
    const [activeButton, setActiveButton] = useState<string>();
    const [ourData, setOurData] = useState();

    useEffect(() => {
        const pa = pathName.split(/[/]/);
        setActiveButton(prev => pa[3])
    }, [pathName])

    useEffect(() => {
        // console.log('saad: ', status);
        if (status === 'authenticated') {
            console.log('saad: ', status);
            fetch(`http://localhost:3000/api/assignment?course_id=${course_id}&teacher_id=${teacher_id}&student_id=${student_id}`, {
                method: 'GET',
                headers: {
                    authorization: `Bearer ${session.user.accessToken}`
                }
            }).then(res => res.json()).then(data => { setOurData(prev => data); console.log(data) })
        }
    }, [status])


    // const {data:session} = useSession();

    if (status === 'authenticated' && ourData) {
        // console.log(ourData)
        return (
            <section>
                <div className="md:ml-[90px] mx-6 mb-4">
                    <div className="my-4 px-2 pt-2 pb-8 bg-white border-2 shadow-md h-auto flex flex-col items-start">
                        <p className="text-3xl sm:text-4xl ml-4 my-2 font-medium tracking-normal leading-relaxed select-none">
                            {/* {ourData[0].course_name} */}
                        </p>
                        <div className="mt-4 ml-4 flex flex-wrap">
                            <div className="py-2 px-4 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-md">
                                <Link href={"/"} className="hover:underline">
                                    Dashboard
                                </Link>
                            </div>
                            <div className="py-2 px-4 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-md">
                                <Link href={"/"} className="hover:underline">
                                    My Courses
                                </Link>
                            </div>
                            <div className="py-2 px-4 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-md">
                                <Link href={"/"} className="hover:underline">
                                    Spring 2023
                                </Link>
                            </div>
                            <div className="py-2 px-4 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-md">
                                <Link href={"/"} className="hover:underline">
                                    Computer Science
                                </Link>
                            </div>
                            <div className="py-2 px-4 bg-slate-100 mr-2 mb-2 lg:mb-0 rounded-md">
                                <Link href={"/"} className="hover:underline">
                                    CS-2103-CS-222-BS-CS-4C
                                </Link>
                            </div>
                        </div>
                    </div>
                    <div className="border-2 border-t-2 border-t-black p-2 flex flex-wrap">
                        <Link href={{ pathname: "/my/course/material", query: { course_id, student_id,teacher_id } }} className='flex flex-grow'>
                            <button
                                className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "material"
                                    ? "bg-black text-white"
                                    : "bg-slate-200"
                                    }`}
                            >
                                Lecture Slides
                            </button>
                        </Link>
                        <Link href={{ pathname: "/my/course/attendance", query: { course_id, teacher_id, student_id } }} className='flex flex-grow'>
                            <button
                                className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "attendance"
                                    ? "bg-black text-white"
                                    : "bg-slate-200"
                                    }`}
                            >

                                Attendance

                            </button>
                        </Link>
                        <Link href={{ pathname: "/my/course/assignment", query: { course_id, teacher_id, student_id } }} className='flex flex-grow'>
                            <button
                                className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "assignment"
                                    ? "bg-black text-white"
                                    : "bg-slate-200"
                                    }`}
                            >
                                Assignment
                            </button>
                        </Link>
                        <Link href={{ pathname: "/my/course/quiz", query: { course_id, teacher_id, student_id } }} className='flex flex-grow'>
                            <button
                                className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "quiz"
                                    ? "bg-black text-white"
                                    : "bg-slate-200"
                                    }`}
                            >
                                Quiz
                            </button>
                        </Link>
                        <Link href={{ pathname: "/my/course/announcement", query: { course_id, student_id,teacher_id } }} className='flex flex-grow'>
                            <button
                                className={`py-2 px-4 rounded-md shadow-lg m-4 text-center flex-grow ${activeButton === "announcement"
                                    ? "bg-black text-white"
                                    : "bg-slate-200"
                                    }`}
                            >
                                Announcements
                            </button>
                        </Link>
                    </div>
                    <div className="border-2 h-full mt-4 duration-500 p-4">
                        {children}
                    </div>
                </div>
            </section>
        );
    }
}